#!/usr/bin/env bash
set -euo pipefail

if ! [ -e flake.nix ]; then
  cat >flake.nix <<'EOH'
{
  description = "A basic flake with a shell";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShell = pkgs.mkShell {
        nativeBuildInputs = [
          pkgs.bashInteractive
        ];
        buildInputs = [
        ];
      };
    });
}
EOH
fi

if ! grep -qFe 'use flake' ./.envrc 1>/dev/null 2>&1; then
  printf 'use flake\n' >> .envrc
  direnv allow
fi

"${EDITOR:-vim}" flake.nix
