#!/usr/bin/env bash
set -euo pipefail

if ! [ -e shell.nix ] && ! [ -e default.nix ]; then
  cat > shell.nix <<'EOF'
{ ... }:

let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
in
pkgs.mkShell {
  nativeBuildInputs = [
    pkgs.bashInteractive
    # Add dependencies here
  ];
}
EOF
  niv init --nixpkgs-branch nixpkgs-unstable
  "${EDITOR:-vim}" shell.nix
fi

if ! grep 'use nix' .envrc 2>/dev/null; then
  printf 'use nix\n' >> .envrc
  direnv allow .
fi
